// Mapeo revisado persona por persona: nombre crudo (como viene en la nómina) -> nombre corregido (Nombre[s] Apellido Apellido)
const MAPEO_NOMBRES = {
  "Hernández Gómez  Valentina Isabel": "Valentina Isabel Hernández Gómez",
  "Araya García Nicole Antonella": "Nicole Antonella Araya García",
  "Arriagada Gonzalo": "Gonzalo Arriagada",
  "Avalos Aránguiz Marta Del Carmen": "Marta Del Carmen Avalos Aránguiz",
  "Azocar Marambio Thiare Romane": "Thiare Romane Azocar Marambio",
  "Barrera Hennings Carmen": "Carmen Barrera Hennings",
  "Cáceres Pacha Pedro Miguel": "Pedro Miguel Cáceres Pacha",
  "Caricari Condori Lourdes": "Lourdes Caricari Condori",
  "Carvajal Fuentes Alejandra Del Carmen": "Alejandra Del Carmen Carvajal Fuentes",
  "Cavagnola Villegas Angelina Paola": "Angelina Paola Cavagnola Villegas",
  "Cayo Flores Jennifer Lissette": "Jennifer Lissette Cayo Flores",
  "Cervellino Rojas Cathalina Francesca": "Cathalina Francesca Cervellino Rojas",
  "Chacama Gallardo Ady Desydee": "Ady Desydee Chacama Gallardo",
  "Choque Chamaca Daniza Claudia": "Daniza Claudia Choque Chamaca",
  "Choque Mamani Janet Marcela": "Janet Marcela Choque Mamani",
  "Contreras Araya Ximena Del Carmen": "Ximena Del Carmen Contreras Araya",
  "Contreras Ayala Omar": "Omar Contreras Ayala",
  "Cortes Zepeda Josías Ulises": "Josías Ulises Cortes Zepeda",
  "Cortez Mollo Maira Jesús": "Maira Jesús Cortez Mollo",
  "Cruz López Daniela Romina ": "Daniela Romina Cruz López",
  "Delgado Chaura Camila Victoria": "Camila Victoria Delgado Chaura",
  "Demetri Matus Angelica Del Pilar": "Angelica Del Pilar Demetri Matus",
  "Epulef Pacheco Janet Patricia": "Janet Patricia Epulef Pacheco",
  "Fernández Condori José Luis": "José Luis Fernández Condori",
  "Galleguillos Mollo Giselle Nataly De Lourdes": "Giselle Nataly De Lourdes Galleguillos Mollo",
  "García Coria Claudio Javier": "Claudio Javier García Coria",
  "Henríquez Soto Daniela Paz": "Daniela Paz Henríquez Soto",
  "Jofré Escobar Pamela América": "Pamela América Jofré Escobar",
  "Lagos Villalobos Kathleen Tamara": "Kathleen Tamara Lagos Villalobos",
  "Letelier Vives Carol Andrea": "Carol Andrea Letelier Vives",
  "Lorena Mamani": "Lorena Mamani",
  "Lovera Burgos Patricia Alejandra": "Patricia Alejandra Lovera Burgos",
  "Lucay Llanes Lidia Dora": "Lidia Dora Lucay Llanes",
  "Maluenda Cortes Andrea Inés": "Andrea Inés Maluenda Cortes",
  "Manzoni Ibarra Vanessa Loreto": "Vanessa Loreto Manzoni Ibarra",
  "Manzoni Jatamaya Uriza Del Carmen": "Uriza Del Carmen Manzoni Jatamaya",
  "Monsalve Ocampo Álvaro Javier": "Álvaro Javier Monsalve Ocampo",
  "Morales Demetri Guillermo Christian ": "Guillermo Christian Morales Demetri",
  "Nelda Sanchez": "Nelda Sanchez",
  "Nina Flores Cinthia Ivette": "Cinthia Ivette Nina Flores",
  "Pacha Villalobos Yessenia Zenobia": "Yessenia Zenobia Pacha Villalobos",
  "Palta Farias Luis Germán": "Luis Germán Palta Farias",
  "Aguilar Aguilar Paula Andrea ": "Paula Andrea Aguilar Aguilar",
  "Rivera Avalos Melany Loreto": "Melany Loreto Rivera Avalos",
  "Rodríguez Pacheco Vilma Iris": "Vilma Iris Rodríguez Pacheco",
  "Rojas Borquez Wuilices ": "Wuilices Rojas Borquez",
  "Rojas Ticuna Karen Victoria": "Karen Victoria Rojas Ticuna",
  "Sepúlveda Núñez Francisco Javier": "Francisco Javier Sepúlveda Núñez",
  "Soto Espinoza Monserrat Del Transito": "Monserrat Del Transito Soto Espinoza",
  "Tito Mamani Marisol Del Rosario": "Marisol Del Rosario Tito Mamani",
  "Usnayo Apaza Romina Eva": "Romina Eva Usnayo Apaza",
  "Veliz Cofré Aldo Vladimir": "Aldo Vladimir Veliz Cofré",
  "Veliz Contreras Camila Belén": "Camila Belén Veliz Contreras",
  "Vizalla Condori Octavina": "Octavina Vizalla Condori",
  "Zenteno Benavides Valenka Ivonne": "Valenka Ivonne Zenteno Benavides",
  "Godoy Carrasco Ninoska Dominique": "Ninoska Dominique Godoy Carrasco",
  "Balboa Bulnes Fabian Andres ": "Fabian Andres Balboa Bulnes",
  "Mamani Mamani Dina Dolfa": "Dina Dolfa Mamani Mamani",
  "Jara Hidalgo Odalis Arecelli": "Odalis Arecelli Jara Hidalgo",
  "Ormazabal Castillo Cristobal Ignacio": "Cristobal Ignacio Ormazabal Castillo",
  "Cuadra Bravo Katherine Ninoska": "Katherine Ninoska Cuadra Bravo",
  "Bacian Herrera Katherine Francheska": "Katherine Francheska Bacian Herrera",
  "Mamani Nayelli": "Nayelli Mamani",
};
module.exports = MAPEO_NOMBRES;
